### ISSUE TITLE
[Suggestion] Config to disable JEI support of the inscription stamp

### ISSUE THREAD

**Issue by Lykrast** [DaedalusGame/Soot#100]
Since some people don't want the JEI for that or get confused by it, a simple config option to make it not have JEI support would be nice.

_Disclaimer: I don't even know what it is I just made the issue after the discord chat._

**Comment by dong031001** [comment]
Strongly agree since it has confused a lot of my modpack's players.

**Comment by Rsslone** [comment]
Yeah I agree, I am trying to integrate it into my modpack but I might remove soot unless I can find a fix for this.
