### ISSUE TITLE
Soot + Mod Creature Incompatability

### ISSUE THREAD

**Issue by Vantageright** [DaedalusGame/Soot#101]
Game crashed seemingly without reason, game states this mod had issue with the wither witch from EnderZoo from what I can tell. [The crash log.](https://paste.dimdev.org/ulixicoxus.mccrash)

Edit: I tried going right back into the world after posting this, it crashed again immediately as expected but this time a creature from Grimoire of Gaia was the one. [Crash log 2 electric boogaloo](https://paste.dimdev.org/ragoxequwo.mccrash)

**Comment by DaedalusGame** [comment]
i no longer use OpenBoolean2Object hashmap. Update Soot.
