### ISSUE TITLE
Crash during initialization

### ISSUE THREAD

**Issue by danzio** [DaedalusGame/Soot#102]
Hi! Got a crash during initialization, crash report at included file.
[crash-2019-08-12_16.14.41-client.txt](https://github.com/DaedalusGame/Soot/files/3492627/crash-2019-08-12_16.14.41-client.txt)

**Comment by DaedalusGame** [comment]
update embers

**Comment by danzio** [comment]
Oh, my bad, sorry! Thank you very much!
