### ISSUE TITLE
ticking entity with experience orbs

### ISSUE THREAD

**Issue by TheXTrunner** [DaedalusGame/Soot#107]
https://paste.ee/p/2Dejl

**Comment by TeetoKaziim** [comment]
Crash seems to happen when player is killed. Happens in a instance with only Embers Rekindled and Soot.

https://hastebin.com/hopicagevu.sql

**Comment by TheXTrunner** [comment]
i didn't die actually, I turned on my experience farm there then my game crashed

**Comment by Darkmega18** [comment]
oh, have been having an xp based death crash. so, hopefully this is the one then that just got posted on curse then.

**Comment by TheXTrunner** [comment]
well I updated and no crash happened with my xp farm so I think it's fixed xd
