### ISSUE TITLE
brew effects have no duration

### ISSUE THREAD

**Issue by lag42** [DaedalusGame/Soot#108]
brew effects have no duration effectively meaning they have no effects, the [alchemical gauge shows the effect exists, but no duration for it](https://imgur.com/a/vsJZdwE), this happens no matter how many times i filter it or add redstone and the creative inventory brews also seem to have this problem

versions:
soot: 1.8
embers rekindled: 1.14-hotfix
forge: 14.23.5.2854

**Comment by DaedalusGame** [comment]
whoops
