### ISSUE TITLE
Crash after placing item pipe

### ISSUE THREAD

**Issue by Chubzik1** [DaedalusGame/Soot#110]
I have crashed, right after placing item pipe from Embers Rekindled next to brewing still tap, and if i trying to join the world it crashes again
There is crash-report
https://pastebin.com/9qJ1zRNe

**Comment by DaedalusGame** [comment]
update embers rekindled

**Comment by Chubzik1** [comment]
oh, dunno how i missed the update, i'll try it

**Comment by Chubzik1** [comment]
Works fine thanks
