### ISSUE TITLE
[1.12] Server Crash when interacting with villager

### ISSUE THREAD

**Issue by MasterEnderman** [DaedalusGame/Soot#16]
Only the Server crashes, while all clients only get kicked.

Crash Report: https://pastebin.com/yjHcu7hM
Forge: 14.23.1.2602
Embers: 0.230
Soot: 0.5

**Comment by DaedalusGame** [comment]
is this really happening i was hoping for the hackiest part to just never break but ok

**Comment by b0bst3r** [comment]
Also happens with Galacticraft villagers on the moon since they do not use emeralds to trade with.  Get the same server crash.

**Comment by b0bst3r** [comment]
With the moon villagers this crash occurs 100% of the time as soon as you interact with the villager, so if you're looking for replication it's an easy one to get to re-occur.

**Comment by DaedalusGame** [comment]
this happens 100% of the time with every villager i'm 99% sure

**Comment by DaedalusGame** [comment]
This is awful because i basicly have to remove the whole thing. It can never work this way.

**Comment by DaedalusGame** [comment]
I've fixed this and will release this soonish.
