### ISSUE TITLE
[Bug] Melter Removal by Input Not Working

### ISSUE THREAD

**Issue by Tetrajak** [DaedalusGame/Soot#18]
Minecraft Version: 1.12.2
Forge Build: 2611
Mod Version: 0.5

Sample script:
#modloaded embers
#modloaded soot
import mods.embers.Melter;
Melter.remove(\<embers:plate_gold\>);

This script does not throw an error, but it fails to remove the Melter recipe for a gold plate into molten gold.

**Comment by DaedalusGame** [comment]
Melter.remove(<embers:plate_gold>);

**Comment by Tetrajak** [comment]
Github has indeed eaten the greater than and less than symbols. I've escaped them to fix it to what it's meant to be.

**Comment by DaedalusGame** [comment]
can i get uhhh minetweaker log

**Comment by Tetrajak** [comment]
Here's the log for the entire Embers script I've written; https://pastebin.com/KzKRQCe4

**Comment by DaedalusGame** [comment]
Hey sorry for taking so long to reply, you can (and have to) use `Melter.remove(<ore:plateGold>)`

**Comment by codetaylor** [comment]
In my experience with CT, overloading methods with the same number of parameters doesn't work as expected.

For example:

```
void remove(IItemStack);
void remove(ILiquidStack);
void remove(IOreDictEntry);
```

Won't work properly, but renaming to:

```
void removeByInput(IItemStack);
void removeByOutput(ILiquidStack);
void removeByOreDict(IOreDictEntry);
```

Should fix the problem.

**Comment by DaedalusGame** [comment]
oof i remember that one

**Comment by DaedalusGame** [comment]
everything should work normally now and also the integration is now moved to Embers itself
