### ISSUE TITLE
Molten ExU2 metals have broken textures if Embers and TCon are installed

### ISSUE THREAD

**Issue by Fortist** [DaedalusGame/Soot#19]
Theres a bug with Embers and Exutil2, where the various liquid forms of Exutil2 metals are texture broken for Tcon.

Why tell you this? Maybe, you'd possibly be able to figure it out, since you're working with embers, and I dont think it's a problem on ExU's side, or Tcon's side.

If you find something, thats cool.
If not, oh well.

**Comment by DaedalusGame** [comment]
god i hate these issues, this happens if a mod registers their fluids incorrectly, how incorrently I have no idea, but AFAIK Embers does not register molten Exutil2 metals, unless you mean stuff like molten gold is broken.

**Comment by DaedalusGame** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/3037
now we wait

**Comment by DaedalusGame** [comment]
Ok so I made a seperate mod that can fix this for all mods that have this issue.
[Let me know if this works](https://minecraft.curseforge.com/projects/what-fluid-fix)
