### ISSUE TITLE
[request] remove anvil recipes

### ISSUE THREAD

**Issue by Efimero** [DaedalusGame/Soot#21]
I'd like to have a way to remove the Dawnstone Anvil's ability to uncraft items, because it does not account for the cost to make them.
For example, a Bone Sword from Pam's Bonecraft, made from bones, will break into two iron ingots (???).
Disabling this functionality would be great for balance in packs that change how weapons are made.

**Comment by DaedalusGame** [comment]
oh right this was on my todo a while back, a simple blacklist will probably suffice

**Comment by DaedalusGame** [comment]
Done. You can now use DawnstoneAnvil.remove(bottom,top) to remove specific recipes.
To remove the recipe in question, you'd do `DawnstoneAnvil.remove(<bonecraft:bone_sword>,<*>);`
