### ISSUE TITLE
Ore Transmute Load Crash With rftools

### ISSUE THREAD

**Issue by ewsmith** [DaedalusGame/Soot#26]
rftools dimensional ore make things crashy with the transmute stuffs.

[https://pastebin.com/S9FNDh45](https://pastebin.com/S9FNDh45)

**Comment by DaedalusGame** [comment]
https://github.com/McJtyMods/RFTools/blob/59088e53e3729f45524294b82441926694dd2ae7/src/main/java/mcjty/rftools/ForgeEventHandlers.java#L85

peachy
i'll think about how to work around this.

**Comment by MinecraftArchive** [comment]
Hate to reopen but its not fixed in 0.11
