### ISSUE TITLE
Glimmer Lights Connect to Fences and Walls

### ISSUE THREAD

**Issue by TechnoMysterio** [DaedalusGame/Soot#32]
I understand the glimmer crystal/lights are from Embers and not Soot, but since Soot seems to be the main place to find updates and bugfixes for Embers since it was discontinued, I'm going to post it here. Anyway, as it says in the title, lights from the glimmer crystal connect to fences and walls, which seems odd.

**Comment by DaedalusGame** [comment]
this is a problem on basicly all embers blocks. i would like to crusade for proper BlockFaceShape integration in all mods but as Embers itself isn't actively developed and the fix in Soot would require overrides for every single block in Embers, I will not put this fix in Soot. (But another solution may present itself sometime in the future)

**Comment by DaedalusGame** [comment]
https://github.com/DaedalusGame/EmbersRekindled/issues/1
