### ISSUE TITLE
[Enhancement] Documentation

### ISSUE THREAD

**Issue by TechnoMysterio** [DaedalusGame/Soot#33]
From what I've seen, you intend to do documentation for Soot at a later date. However, Soot has quite a lot of content that isn't well explained (I'm struggling to understand brewing for instance), perhaps except for limited info from JEI and Crafttweaker stuff in the Github wiki, which is rather frustrating, especially for newer players. It may be wise to write up some documentation for the mod somewhere, perhaps in the form of extra entries for the Ancient Codex book from base Embers. If you need some help, I can write up some stuff in a word doc or something, as long as you explain some stuff in the mod to me.

Actually, speaking of base Embers, I have a quick and somewhat unrelated question: are you getting some of the features for the mod from the 'Embers Plans' document by Elucent on Gist? I'm guessing that you are, since I've noticed things like Alchemical Slurry and Metallurgic Dust in both.

**Comment by DaedalusGame** [comment]
Yes, Alchemical Slurry, Catalytic Plugs, Metallurgic Dust, part of the Ember Bore changes (it now makes Ember Grit additionally) I've taken from the plans document.

I'll see about writing some documentation in the codex if I can find proper space for it. The codex itself is very limited in terms of presentation, so it's only one page of text per entry really and it has no ability to add extra tabs, which is a bit frustrating. This is mainly the reason why I haven't used it yet.

**Comment by TechnoMysterio** [comment]
Ah yeah, Ember Grit, wondered how you got that, as no crushing recipes (like with Immersive Engineering grit) showed up for it in JEI.

Perhaps adding some extra functionality to the Codex to get extra space wouldn't go amiss, especially if you're getting into bigger stuff from the plans document (the mechanical power bit looks very extensive for instance). Maybe something like 'click on the middle circle to switch to five extra pages (flipped upside down perhaps), click on it again to switch back'.

**Comment by DaedalusGame** [comment]
I take that back i can add extra tabs and i can even customize the texture on the little symbol it has. Taking a closer look at it now.

**Comment by TechnoMysterio** [comment]
How does that work then? Will adding an extra tab mean they're positioned like a hexagon instead of a pentagon or something?

**Comment by DaedalusGame** [comment]
yeah, it looks like i have to whack the gui handler anyway though, the icon texture and the x coord on the texture sheet exist but are not respected.
