### ISSUE TITLE
The One Probe Showing Error on Brewing Still

### ISSUE THREAD

**Issue by TechnoMysterio** [DaedalusGame/Soot#34]
This may be to do with TOP Addons, but looking at the Brewing Still shows an error in TOP:

![2018-05-25_18 49 40](https://user-images.githubusercontent.com/5113920/40558810-73f83a4a-604c-11e8-9170-ca5e02442a03.png)
![2018-05-25_18 49 57](https://user-images.githubusercontent.com/5113920/40558812-75d106f8-604c-11e8-9348-24f3e8405ffb.png)

**Comment by DaedalusGame** [comment]
does this output anything in the console because it doesn't for me and i'm not sure where to begin with this
