### ISSUE TITLE
[1.12.2] [0.12hotfix] Ember bore doesn't work 

### ISSUE THREAD

**Issue by wamc2017** [DaedalusGame/Soot#37]
Hi,

the ember bore doesn't work if "Overrides the Ember Bore" is enabled in the config. Seems that it doesn't accept any coal... (Disabling the override makes it work again.)

Maybe that's not a bug and the ember bore works different now with the override, but I can't find any information about the changes soot made to the bore... :smile:

Versions I used to test this problem:
Baubles-1.12-1.5.2
embers-0.230
jei_1.12.2-4.9.1.191
Soot-0.12hotfix
forge-14.23.4.2703

Thanks for looking into it. :)

Best regards,
wamc2017

**Comment by DaedalusGame** [comment]
can't confirm this one, it seems to work fine for me.

**Comment by wamc2017** [comment]
![2018-05-26_02 15 27](https://user-images.githubusercontent.com/33242447/40570412-dcf8c940-608a-11e8-8f9e-a34b11336154.png)

Hmm, very basic setup, 1x bore, 1x core, 2x pipes, 2x extractors, 2x chests, 2x levers. The levers are turned on and I put coal into the left chest, it gets sucked up, but is stuck in the pipe and doesn't insert into the core...

I used only the mods listed above in this instance!

**Comment by DaedalusGame** [comment]
right, i'll test it with the pipes.

**Comment by wamc2017** [comment]
Oh, didn't think about that and tried it with a hopper and it works fine to insert the coal... :smile:

**Comment by DaedalusGame** [comment]
and just like that folks Embers takes it home again because for some lovely reason its pipes will cancel insertion if the slot is empty but can't be inserted. I can get this working I just need to stare at it for a few minutes.
