### ISSUE TITLE
The One Probe Showing Error on Exchange Tablet

### ISSUE THREAD

**Issue by TechnoMysterio** [DaedalusGame/Soot#40]
The sequel to the critically acclaimed 'The One Probe Showing Error on Brewing Still', and this time, it's personal:

![2018-05-26_17 11 05](https://user-images.githubusercontent.com/5113920/40578195-dcffe400-6107-11e8-9192-cca9e1cfde96.png)

**Comment by DaedalusGame** [comment]
extremely classic as the scales don't have any capabilities

**Comment by TechnoMysterio** [comment]
Told you it was personal.
