### ISSUE TITLE
[Enhancment] Sounds - With Demo Video

### ISSUE THREAD

**Issue by TechnoMysterio** [DaedalusGame/Soot#41]
While I've always felt that Embers was a interesting and artistically pleasing mod, it always lacked a certain level of punch that other mods have. I think this may be in part due to its lack of sounds. The various things you do in the mod certainly look spectacular, but they're almost always completely silent, save for a few things that use vanilla MC sound effects.

For instance, the Alchemy System looks very impressive, with very elaborate particle systems and effects, but it has no sound. Compared to something like Thaumcraft's Infusion system or Astral Sorcery's altar crafting, which are both similarly fancy but also have sounds, Embers feels somewhat lacking. As such, I've made a mockup video to showcase some sounds I designed for the alchemy system. It might need a little work, but it could certainly help the mod shine:

https://www.youtube.com/watch?v=ttF4ZLL6Tms

I broke the event down into a few parts: the beam cannon firing, the alchemy process starting, a background loop for the alchemy process, a loop for the sound of ash being taken from separate pedestals, and the success/failure of the item being crafted. The video is a just me using some video editing software to overlay the separate sounds together, no programming involved.

I understand sound is usually an afterthought when it comes to Minecraft mods, but do have a look over the video, sounds might help give the mod a little more substance.

**Comment by DaedalusGame** [comment]
I'd like to have sounds but the problem is making/getting them. If you want to hook me up with some I'll implement them.

**Comment by TechnoMysterio** [comment]
Sure, that's what the video was showing. Just let me know what you want and where to upload them.

**Comment by DaedalusGame** [comment]
right any upload site works for me or you can hit me up on discord (Bord Listian)
i vaguely recall that i have a sound for the activator and the crystal cell but i'm not sure where

**Comment by TechnoMysterio** [comment]
Here's what I've done so far on MEGA (beam cannon, alchemy sounds):

https://mega.nz/#!pPxAkSjL!YG2MUZwLeMJqKcWvnYEZNNLORM7QWxohU_lIAg9trzo

Feel free to look over them in whatever audio software you have. I'll probably do some work on some other stuff tomorrow, maybe the Bore and Golems. And I don't use Discord that much, but I'll have a look.

**Comment by DaedalusGame** [comment]
Greatly appreciated, that.

**Comment by TechnoMysterio** [comment]
Actually, two things to mention: one, I forgot to do a sound for the beam hitting an object, so I'll probably work on that at some point, and secondly, do you think a sound for the beam cannon charging up would make sense? It might, as the main problem with the beam cannon is that you can't tell whether it's working or not before it annihilates you, seemingly at random, so an audio cue might help to inform players as to what's going on with it.

**Comment by DaedalusGame** [comment]
I think I will change the beam cannon to fire at will if it has enough ember to fire instead of the modulo based cooldown

**Comment by TechnoMysterio** [comment]
Yeah, that sounds better, and it means I have less work to do, so it's a win-win.
