### ISSUE TITLE
[1.12.2] [0.15] Can't craft Infused Aetherium Tool Rod from Aetherworks (cross compatibility)

### ISSUE THREAD

**Issue by wamc2017** [DaedalusGame/Soot#42]
Hi,

tried to craft the Infused Aetherium Tool Rod from Aetherworks today and the process doesn't start if "Overrides the Exchange Tablet" is true in the config. That's the only recipe I've found which doesn't work, the recipe looks like this:

![untitled](https://user-images.githubusercontent.com/33242447/40795219-a71a9990-6501-11e8-80fe-401c9737065f.png)

I think it's a problem with empty input sides, but don't know for sure.

Mods I used to test this problem (no other mods installed):
jei_1.12.2-4.9.2.196
embers-0.230
AetherWorks-1.12.2-1.0.0.3
Soot-0.15
forge-14.23.4.2705

If I should report it to Aetherworks issue tracker as well, let me know and I'll do it. :)

Thanks for looking into it.

Best regards
wamc

Edit: Played a little bit around with crafttweaker and removed and readded the recipe and it's working fine, so maybe it's an issue with converting the recipe?

`mods.embers.Alchemy.remove(<aetherworks:item_resource:8>);
mods.embers.Alchemy.add(<aetherworks:item_resource:8>,[<aetherworks:item_resource:7>,null,null,null,null],12 to 16,12 to 16,12 to 16,12 to 16,12 to 16);`

**Comment by DaedalusGame** [comment]
interesting, I've tested this on a related sideproject and it works fine, so it must be a migration issue.

**Comment by wamc2017** [comment]
Hmm, have tried it several times and I'm able to replicate it by installing all mods from scratch, so don't know if this only is an issue on my side... (The setup works fine, because after disabling "Overrides the Exchange Tablet", replacing the exchange tablet and retrying it works fine, also after using the script...)

Personally I could use the script posted above to fix it as long this problem exists for me. :)

**Comment by DaedalusGame** [comment]
I double-checked this outside of my dev environment and still cannot reproduce so i'm not sure what happened in your case. Maybe it's related to a forge change...

**Comment by wamc2017** [comment]
Hmm, strange I made a complete new instance copied my testworld over (where everything was set up) and it worked flawlessly (did the exact same thing yesterday about 5 times...)

Sorry for bothering you with this, I call it gremlins... :/
