### ISSUE TITLE
Embers fluid tanks don't update their fluid display when used in conjunction with other mods' fluid transport

### ISSUE THREAD

**Issue by build2stone** [DaedalusGame/Soot#43]
This appears to be a bug in Embers, and while not critical, it is somewhat annoying. Due to the current state of Embers, I figured I'd put this here.

Basically the title. It seems that any method of extracting or inputting fluids other than buckets or the fluid pipe and extractor from Embers causes the Embers tanks (i.e. the Fluid Vessel, Reservoir and Stamp Base) not to update their fluid display. Fluid Dials also don't work. Attempting to interact with the tank with a bucket or fluid pipe and extractor updates the tank display, as does relogging.

Tested using forge-14.23.4.2705, embers-0.230 and various mods with fluid transport

**Comment by wamc2017** [comment]
https://github.com/DaedalusGame/EmbersRekindled/issues should be the better issue tracker to report ember bugs... ;)

**Comment by build2stone** [comment]
That's a thing? Cool! Guess I'll go put this there then.
