### ISSUE TITLE
Allow ore from this mod to be used in Thaumcraft's ore cluster system

### ISSUE THREAD

**Issue by Sunconure11** [DaedalusGame/Soot#45]
For some reason, Embers ores are not valid for duplication via clusters.

**Comment by Sunconure11** [comment]
I decided to pull up my game again now that Thaumcraft released a more stable build. Still not seeing recipes for embers ores with Thaumcraft. I am using Thaumic JEI to look for said recipes.

**Comment by DaedalusGame** [comment]
fixed in embers
