### ISSUE TITLE
[0.15] Ember Funnel doesn't work

### ISSUE THREAD

**Issue by Shandoo94** [DaedalusGame/Soot#46]
Like the title says, I am unable to input Ember into a Crystal Cell with an Ember Funnel. I am going ova a Machine Accessor. If i replace the funnel with a receptor the Ember is injected normaly.

**Comment by DaedalusGame** [comment]
Could you post a screenshot of your setup?

**Comment by Shandoo94** [comment]
I got this setup to work in a testworld, but it is very unreliable. It doesn't work most of the time. Even just activating one Ejector doesn't help. Puting the funnel on an Accesor never works, so I guess it isnt intended to be used that way.

Each side of Ejectors feeds a Funnel on the respective side.

![2018-06-03_18 54 05](https://user-images.githubusercontent.com/21018028/40888994-c335a65a-675f-11e8-8143-340c7c13d189.png)
![2018-06-03_18 54 13](https://user-images.githubusercontent.com/21018028/40888995-c3534dc2-675f-11e8-9172-750f979fad66.png)
![2018-06-03_18 54 20](https://user-images.githubusercontent.com/21018028/40888996-c36cbf78-675f-11e8-8d93-f9edc3bf3ee9.png)
![screen1](https://user-images.githubusercontent.com/21018028/40888997-c387e3fc-675f-11e8-9cdd-121c6a4e151f.png)

**Comment by DaedalusGame** [comment]
this is basicly solved in an Embers Rekindled build i believe. Ember containers now mark dirty when they change their contents.
