### ISSUE TITLE
Soot Crashes on Launch

### ISSUE THREAD

**Issue by IronPiston** [DaedalusGame/Soot#56]
Using Embers Rekindled and Soot 1.0, alongside Forge 14.23.4.2713, Soot causes a crash before the game gets to the main menu.

Here is the pastebin: https://pastebin.com/4Q1FbKVe

Note that this is a modded environment using only Embers, Soot, and Forge.

**Comment by wamc2017** [comment]
I think Soot 1.0 is only compatible with Dev Build 2 which is only available on the embers github: https://github.com/EpicSquid/Embers/releases
