### ISSUE TITLE
Melter Remove Recipe Not Working

### ISSUE THREAD

**Issue by Boolyman** [DaedalusGame/Soot#58]
I'm attempting to remove Alchemical Slurry from being processed from redstone int he Melter, as I want Destabilized Redstone to come out of it instead.  The syntax I am using is below...

mods.embers.Melter.remove(<liquid:alchemical_redstone>);
mods.embers.Melter.add(<liquid:redstone>, <minecraft:redstone>);

I am getting no errors from Crafttweaker using that syntax, but when I process redstone through the melter it still comes out as Alchemical Slurry.

**Comment by DaedalusGame** [comment]
should be exact amount for removal so try `mods.embers.Melter.remove(<liquid:alchemical_redstone>*144);`

**Comment by Boolyman** [comment]
Works!  Thank you.
