### ISSUE TITLE
[1.12] [Soot 0.4 Hotfix] Rustic Ale Texture Issue

### ISSUE THREAD

**Issue by TechnoMysterio** [DaedalusGame/Soot#6]
When looking at Rustic's alcohols in JEI, the basic ale shows up as purple and black, and apparently comes from Soot, according to the tooltip. 

![rustic soot imcompat 25-11-17](https://user-images.githubusercontent.com/5113920/33232205-b6d0191e-d1f9-11e7-88cd-a6abb9887988.png)

This only affects my older words for some reason, as newer saves have no texture issue and the tooltip says it's from Rustic. I'm not sure why, and I've had similar glitches before, but it might be a good idea to rename it (Dwarven Ale or something) for compatibility's sake when Soot's brewing system isn't a WIP.

**Comment by DaedalusGame** [comment]
This is related to how forge handles several liquids with the same id internally, if both Soot and Rustic are setup correctly, this should create no problems (other than no texture)

**Comment by TechnoMysterio** [comment]
Managed to fix it, just had to alter the fluid list in the save's nbt file. Closing.
