### ISSUE TITLE
Found a strange bug/crash with Soot

### ISSUE THREAD

**Issue by Convergence2738** [DaedalusGame/Soot#61]
I was playing around melting ores using the melter and found a strange bug/incompatibility with the Stamper. For some reason JAOPCA doesn't play nice now with your Soot override (it used too, but not atm). I am using some Immersive Engineering uranium to test it. When in the stamper base, the stamper does not process the liquid uranium despite the recipe being present (in JEI). Your override with JAOPCA literally made the melter/stamper mod cross-compatible with almost all mods. I got a crash to trigger when removing your override then looking at the stamper recipe tab or when simply disabling the migrating Stamper recipes option in the config. 
[crash-2018-07-06_12.59.21-client.txt](https://github.com/DaedalusGame/Soot/files/2171835/crash-2018-07-06_12.59.21-client.txt)

EDIT: nvm, it crashes even after reverting. I'll remove JAOPCA then reload it to see if that fixes that.

**Comment by Convergence2738** [comment]
ok...Removed JAOPCA and the crash still procced. I am now going to remove Soot itself and see if the JEI crash disappears.

**Comment by DaedalusGame** [comment]
i can't help with that crashlog, it refers to codechickenlib and chisel, not soot.

**Comment by Convergence2738** [comment]
yeah, I confirmed that when I removed soot and the crash still procced. It's still really weird though. Because it made the Stamper...just not work. Copper still worked with the stamper. I will have to check the codechickenlib for updates and chisel then.

**Comment by Convergence2738** [comment]
yeah...updated codechickenlib, it's still broken. I don't want I did with the configs but it's completely borked now. I'll have to remove codechickenlib, but a good number of mods used that as a base. The chisel mod isn't a part of it it seems, removal didn't nothing to stop the crash. 
To any others with codechickenlib in their game, be careful if you play with your Soot config.

**Comment by wamc2017** [comment]
Looks like the same issue as https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63

Upgrade CTM or downgrade forge...

**Comment by Convergence2738** [comment]
wow....CTM srsly? Well, I'll give it a go and see if that fixes this bizarre stamper problem.

**Comment by Convergence2738** [comment]
Yeah, the CTM update fixed the stamper JEI crash, but the silly stamper bug remains. 

here: are some pics of it It's super bizarre. 
![20180706140116_1](https://user-images.githubusercontent.com/36319508/42400213-391f3f9c-8160-11e8-97c6-894cb5164c03.jpg)
![20180706140138_1](https://user-images.githubusercontent.com/36319508/42400219-3c8dc0a4-8160-11e8-81c1-9669f12cdda5.jpg)

**Comment by Convergence2738** [comment]
Alright. I played with it some and yeah. It's something to do with the Soot Stamper plates I think. Because I remove the Stamper override in the config and the JAOPCA processing recipes work just fine with the Stamper (like literally all of them), but when I use the Soot Stamper, even though the ingot recipe *should* work, it doesn't want to. Ember ores process fine, but all other ores do not want to. The plates are visually different on the Soot Stamper from the plain Embers one.

**Comment by DaedalusGame** [comment]
Well, it's a moot point because all of this is already rolled into rekindled anyway
