### ISSUE TITLE
Ember Grit clogs ember activators and pressure refinery

### ISSUE THREAD

**Issue by Cronock92** [DaedalusGame/Soot#64]
I'm mostly certain this is an issue with Soot's ember grit in item tubes, but it could be fixed if an issue with Embers' Item Transfers was fixed. Because Embers' Item Transfers aren't working properly as of the most recent update, you can't filter out Ember Grit from your item tubes. So when it is extracted with ember shards and crystals, it clogs up the tube (which might be on Embers end) so the ember activators and pressure refineries will stop working if you have a tube connected.

**Comment by Cronock92** [comment]
It is also an item pipe issue. If grit is the first item in line all other items, e.g. shards and crystals, can't pass through. I was doing testing on auto workarounds for this for the last half hour. Short of a redstone sorter, this is a big issue for automation.

**Comment by DaedalusGame** [comment]
i'm told thats how the pipes are supposed to work but they're still dumb

**Comment by DaedalusGame** [comment]
basicly fixed a long time ago in rekindled
