### ISSUE TITLE
High CPU load in GolemHandler.isGolem

### ISSUE THREAD

**Issue by LemADEC** [DaedalusGame/Soot#66]
As found while analyzing a profile for another issue regarding the Transcendence modpack:
GolemHandler.isGolem() is doing lookup into forge registry every tick, consumming 1.40% doing so. Consider using instanceof or cached entityId instead.

![image](https://user-images.githubusercontent.com/4776032/44487389-7aa78f80-a656-11e8-9189-fbc96bd5f088.png)

**Comment by DaedalusGame** [comment]
already fixed
