### ISSUE TITLE
[JEI] Recipe for alchemical recombulator is sometimes wrong

### ISSUE THREAD

**Issue by ThatGamerBlue** [DaedalusGame/Soot#67]
If you press U on and Archaic Circuit to get to the recipe it shows the ashes go on Dawnstone and Lead which is wrong. However if you press R on the recombulator it shows the correct recipe of Copper+Lead Aspectuses (aspecti?)

https://i.imgur.com/K6fbSWL.png (U on circuit)
https://i.imgur.com/5XULzoJ.png (R on recombulator)

Soot version: 0.18hotfix
Embers version: 0.230
JEI version: 4.11.0.206

**Comment by DaedalusGame** [comment]
update Soot to 1.x+ and Embers to Embers Rekindled
