### ISSUE TITLE
[1.12.2] [1.4+] Alchemical Recombulator doesn't work

### ISSUE THREAD

**Issue by wamc2017** [DaedalusGame/Soot#70]
Hi,

here is my setup: 
![2018-09-10_17 41 54](https://user-images.githubusercontent.com/33242447/45308086-f9d70780-b520-11e8-8317-3c405cd2a292.png)

It works fine with Embers Rekindled 1.4hotfix and Soot 1.3hotfix. If I update to Embers Rekindled 1.5hotfix (or newer), nothing happens... (unless something changed how to use the recombulator, I guess that's a bug)

Tested it with only Embers, Soot and JEI installed.

Thanks for looking into it.

Best regards,
wamc

**Comment by DaedalusGame** [comment]
oh smoke i knew i broke something when i poked around machine upgrades

**Comment by wamc2017** [comment]
Any news on this?

**Comment by anders0nmat** [comment]
well are there news about this?
bc im currently playing a modpack where antimony is part of the progress, would feel bad if i have to cheat

**Comment by TheFlipflop** [comment]
@DaedalusGame any updates on this? :)

**Comment by thehemmo** [comment]
well the code seems to be bit spaghetti and there is little comments in the code. I can see that something what calls the ejectFailure method may be causing the problem. just guess.

**Comment by ManIkWeet** [comment]
This is a lovely bug...

**Comment by werwin11** [comment]
Playing this mod in MSB3 gated and cannot complete the 16 Antimony ingot task to progress. There is no fix in sight?

**Comment by ManIkWeet** [comment]
I guess not in the near future, you'll have to cheat them in :(

(Or maaaaaaaybe downgrading Soot might work, the last update broke it)

**Comment by jonuhal** [comment]
It's broken for me using MSB3 server 3.6.0 files that contain Soot-1.3hotfix.jar. I also installed the latest Soot-1.5.jar to try this but that is broken as well. Did not try reverting previous to Soot-1.3hotfix.jar.

**Comment by iarspider** [comment]
@DaedalusGame I think have a bit of insight on what's wrong. In [mixer code](https://github.com/DaedalusGame/EmbersRekindled/blob/rekindled/src/main/java/teamroots/embers/tileentity/TileEntityMixerBottom.java#L190) you are only looking for regular FluidMixingRecipe, and 
quit early if a recipe is not found. In [Soot code ](https://github.com/DaedalusGame/Soot/blob/master/src/main/java/soot/recipe/CraftingRegistry.java#L131) the recipe for Antimony is registered as AlchemicalMixingRecipe, which belongs to it's own Registry.

**Comment by iarspider** [comment]
I'm a total n00b when it comes to writing MC mods, but one option to fix this would be to add `isRecipeValid` to upgrades and call it if recipe is not found in regular registry, and only quit if Upgrade returns `False`.

**Comment by imi0** [comment]
Ran into this when playing Modern Skyblock 3 Departed. I updated to EmbersRekindled-1.14-hotfix.jar and Soot-1.10-hotfix.jar, but its still not working (or broken again?)

**Comment by darkelfe14728** [comment]
Use Soot-1.6 and EmbersRekindled-1.13-hotfix : works fine for me

**Comment by JakeBaumbaugh** [comment]
Download links to these versions of [Soot](https://www.curseforge.com/minecraft/mc-mods/soot/download/2697925) and [Embers Rekindled](https://www.curseforge.com/minecraft/mc-mods/embers-rekindled/download/2697221) for convenience.

**Comment by Ashen-sysadmin** [comment]
If this is still broken, in latest versions, then this should be re-opened
