### ISSUE TITLE
[1.12.2] [1.5] Game crashes with Embers Rekindled 1.9

### ISSUE THREAD

**Issue by wamc2017** [DaedalusGame/Soot#80]
Hi,

the game crashes if Embers Rekindled is updated to 1.9, if Soot is installed as well:
https://gist.github.com/wamc2017/82892c57b319c969bec1e6f45254a9cf

I guess you've to fix this import:
https://github.com/DaedalusGame/Soot/blob/0e79ed2486bcf83053e9a91d91dff4c4dd1d7797/src/main/java/soot/itemmod/ModifierWitchburn.java#L15

Thanks for looking into it.

Best regards,
wamc

**Comment by Sunconure11** [comment]
https://paste.dimdev.org/putaxeyeno.mccrash

Can confirm the same issue
