### ISSUE TITLE
Crash with Primitive Mobs

### ISSUE THREAD

**Issue by JadeFalcon** [DaedalusGame/Soot#81]
Crash Report: https://paste.dimdev.org/ehijopopoy.mccrash

**Comment by DaedalusGame** [comment]
does this happen more often?

**Comment by JadeFalcon** [comment]
It happened two more times with different entities after that, but I'm able to launch and play the world today with no problems.

**Comment by Cazadorsniper** [comment]
I've been getting reports of this crash quite a bit, this one has to do with a abyssalcraft demon pig:https://gist.github.com/Pival81/bd1e24e6727ca9880aacecfa684a1dc2
