### ISSUE TITLE
[1.5] Brewed Drinks do not display the correct stats

### ISSUE THREAD

**Issue by Shandoo94** [DaedalusGame/Soot#87]
**Version**
Soot 1.5
Embers Rekindled 1.12
Forge 14.23.5.2815

**What happens**
When I brew drinks like ale in the still with effects like healing or lifedrinker, they get applied correctly when I drink it. But the stats displayed in the itemtooltip don't correspond to these effects at all. The additional effects are not listed and the displayed duration is also not correct.

**Comment by DaedalusGame** [comment]
Mug tooltips don't show effects/modifiers past the primary one intentionally so you can trick people into drinking your "super awesome brew" and they can't figure out from the tooltip that it will actually kill them.

**Comment by DaedalusGame** [comment]
there's a dial that shows you the effects if you put it on a fluid container containing the brew

**Comment by Shandoo94** [comment]
ohh, ok I will look at that. Thanks for the help.

**Comment by Shandoo94** [comment]
Is the concentration a modifier to the added effects? Like for example +2 health from the netherwart and a 100% concentration becomes +4 health on consumption?

**Comment by DaedalusGame** [comment]
not currently because concentration adds to the potion effect amplifier but it probably should/will be
