### ISSUE TITLE
CT Melter Liquid Remove doesn't seem to work

### ISSUE THREAD

**Issue by davqvist** [DaedalusGame/Soot#9]
Soot 0.4-hotfix
Forge 2556

I tried both
`mods.embers.Melter.remove(<liquid:iron>);`
and
`mods.embers.Melter.remove(<liquid:iron> * 288);`

Both didn't seem to work.
`[INITIALIZATION][CLIENT][INFO] Removing 0 Melter Recipe(s) for Unknown item`

**Comment by DaedalusGame** [comment]
urgh face meet inside of hand
