### ISSUE TITLE
When using jei, the embossing will register the synthesis resulting in a lag

### ISSUE THREAD

**Issue by mcmso** [DaedalusGame/Soot#95]
When using jei, the embossing will register the synthesis resulting in a lag

**Comment by mcmso** [comment]
> I'm not sure i understand
> 
> is this related to the inscription stamp?

Is that a question?

**Comment by DaedalusGame** [comment]
it's fine, i now understand

**Comment by mcmso** [comment]
> 没关系，我现在明白了

What I want to express is, is the lagging question of my feedback a question?

**Comment by mcmso** [comment]
> it's fine, i now understand

What I want to express is, is the lagging question of my feedback a question?

**Comment by SirAron111** [comment]
Is there a way to make it so not every bloody item in jei shows the stamper recipe for renaming (just don’t show them mention it in the bloody codex that it can rename items and that’s it) literally every item shows up as this stamper confusing the heck out of my modpack players
