### ISSUE TITLE
Specifying no dimensions for the Sulfur Generation whitelist causes game to crash

### ISSUE THREAD

**Issue by Trevor-Mansfield** [DaedalusGame/Soot#97]
I wanted to disable sulfur generation by just saying no dimensions are valid for generation, but the game gets mad when it tries to parse the dimensions inside of the < > and finds nothing, so it gets a null error about the empty string and crashes during startup. Putting a dimension in and saying just make 0 attempts to generate per chunk works fine though.

**Comment by DaedalusGame** [comment]
can you pastebin/gist your crashlog

**Comment by Trevor-Mansfield** [comment]
Yup one sec let me re-edit it and relaunch.

**Comment by Trevor-Mansfield** [comment]
https://pastebin.com/XTuSQtPM

It's actually only if the brackets are like this:
```
... <

> ```
If there is no empty line it doesn't crash.
```
... <
>
``` (fine)

**Comment by DaedalusGame** [comment]
working as intended then

**Comment by DaedalusGame** [comment]
to clarify, since the crash happens in forge code it's basicly working as intended by forge, so none of my biz really

**Comment by Trevor-Mansfield** [comment]
Yeah I just didn't realize it was because there was an empty new line at first until I had tried recreating it and it worked. If theres no line it works fine. Thank you! Have a good day.
